compiler:
    solc:
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
#            - "hardhar=nomiclabs/hardhat@1.3.3"


dependencies:
#    - nomiclabs/hardhat@1.3.3
    - brownie-mix/token-mix@1.0.0  # fixme do we really need this
    - OpenZeppelin/openzeppelin-contracts@3.4.0

